const express = require('express');
const router = express.Router();

const authRoute = require('./auth');
const paysRoute = require('./pays');
const etatRoute = require('./etat');
const langueRoute = require('./langue');
const photosFamilleRoute = require('./photosFamille');
const photosFilleRoute = require('./photosFille');
const contactRoute = require('./contact');
const moyenPaiementRoute = require('./moyenPaiement');
const paiementRoute = require('./paiement');
const utilisateurRoute = require('./utilisateur');
const questionnaireFilleRoute = require('./questionnaireFille');
const questionnaireFamilleRoute = require('./questionnaireFamille');
const questionnaireRoute = require('./questionnaire');
const questionRoute = require('./question');
const reponseRoute = require('./reponse');
const documentsSoumisRoute = require('./documentsSoumis');
const contratRoute = require('./contrat');
const formationRoute = require('./formation');
const examenRoute = require('./examen');

router.use('/auth', authRoute);
router.use('/pays', paysRoute);
router.use('/etat', etatRoute);
router.use('/langue', langueRoute);
router.use('/photosFamille', photosFamilleRoute);
router.use('/photosFille', photosFilleRoute);
router.use('/contact', contactRoute);
router.use('/moyenPaiement', moyenPaiementRoute);
router.use('/paiement', paiementRoute);
router.use('/utilisateur', utilisateurRoute);
router.use('/questionnaireFille', questionnaireFilleRoute);
router.use('/questionnaireFamille', questionnaireFamilleRoute);
router.use('/questionnaire', questionnaireRoute);
router.use('/question', questionRoute);
router.use('/reponse', reponseRoute);
router.use('/documentsSoumis', documentsSoumisRoute);
router.use('/contrat', contratRoute);
router.use('/formation', formationRoute);
router.use('/examen', examenRoute);

module.exports = router;